@base_address = http://localhost:5000/api/Products

GET {{base_address}}
Accept: application/json

###
GET {{base_address}}/5
Accept: application/json


### 
POST {{base_address}}
Content-Type: application/json

{
    "Name": "TableNew",
    "UnitPrice": 400.00
}

### 
PUT {{base_address}}/5
Content-Type: application/json

{
    "Id": 5,
    "Name": "Bottle",
    "UnitPrice": 60.00
}

###
DELETE {{base_address}}/5
